<a href="https://colab.research.google.com/github/DevKumar57-67/Data-Science-Basics/blob/main/Data_Science_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

            DATA SCIENCE TUTORIALS

Data Science and Artificial Intelligence are one of the most fascinating field in the world today. In this particular course we will be looking towards the concepts of Data Science and Artificial Intelligence.

This course is sub-divised in the chapters:

Machine Learning concepts
Deep Learning concepts
Natural Language Processing concepts
Generative AI

All the chapters will be covered deeply

Prerequisites:
Some prerequisites are needed for learning DS and AI.
Cover the Python Programming Language completely and then a Database and Data Structures and Algorithms in Python

                MACHINE LEARNING
* Data Science Basics
* Data Loading
* Data Analytics
* Data Processing
* Data Visualisation
* Web Scrapping
* Data Science Libraries
* Pandas
* Numpy
* Matplotlib
* Pyplot
* Seaborn
* Supervised ML
* Unsupervised ML
* Reinforcement ML
* ML Algorithms

In [ ]:
# Data Loading with pandas for csv types of files
import pandas as pd
df = pd.read_csv("/content/global_water_consumption.csv")
df.head()

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
0,Indonesia,2022,895.15,489.73,Low,20.78,13.75,34.99,1075.28,3.10
1,Indonesia,2024,502.89,311.95,High,48.51,8.44,32.88,2630.69,1.78
2,Spain,2000,843.39,440.09,Medium,25.16,31.70,34.62,2860.62,4.13
3,Canada,2021,803.34,478.98,High,45.74,6.13,18.99,1725.50,0.61
4,Brazil,2022,416.40,353.91,High,26.58,7.95,31.11,988.44,0.80

In [ ]:
#Data Analytics with CSV files
df.head(5) # for top 5 rows

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
0,Indonesia,2022,895.15,489.73,Low,20.78,13.75,34.99,1075.28,3.10
1,Indonesia,2024,502.89,311.95,High,48.51,8.44,32.88,2630.69,1.78
2,Spain,2000,843.39,440.09,Medium,25.16,31.70,34.62,2860.62,4.13
3,Canada,2021,803.34,478.98,High,45.74,6.13,18.99,1725.50,0.61
4,Brazil,2022,416.40,353.91,High,26.58,7.95,31.11,988.44,0.80

In [ ]:
df.tail(5) #for bottom 5 rows

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
4995,Japan,2018,959.42,143.62,Low,25.19,49.05,10.97,1054.31,4.72
4996,China,2018,642.35,444.26,Medium,66.37,21.20,21.43,1342.62,2.13
4997,UK,2005,848.58,286.60,High,33.97,39.06,31.87,783.17,0.48
4998,Australia,2005,544.67,450.18,Low,64.19,18.74,21.35,1584.80,0.56
4999,Italy,2019,420.13,198.42,Medium,53.89,9.77,10.17,2161.10,2.06

In [ ]:

#for knowing number of rows and columns
print(df.shape)

(5000, 10)

In [ ]:

# for n rows
df = pd.read_csv("/content/global_water_consumption.csv", nrows=3)
df

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
0,Indonesia,2022,895.15,489.73,Low,20.78,13.75,34.99,1075.28,3.10
1,Indonesia,2024,502.89,311.95,High,48.51,8.44,32.88,2630.69,1.78
2,Spain,2000,843.39,440.09,Medium,25.16,31.70,34.62,2860.62,4.13

In [ ]:
# for skipping the rows
df = pd.read_csv("/content/global_water_consumption.csv", skiprows=4999)
df

  Australia  2005  544.67  450.18     Low  64.19  18.74  21.35  1584.8  0.56
0     Italy  2019  420.13  198.42  Medium  53.89   9.77  10.17  2161.1  2.06

In [ ]:

# for basic math
df.describe()

         2005  544.67  450.18  64.19  18.74  21.35  1584.8  0.56
count     1.0    1.00    1.00   1.00   1.00   1.00     1.0  1.00
mean   2019.0  420.13  198.42  53.89   9.77  10.17  2161.1  2.06
std       NaN     NaN     NaN    NaN    NaN    NaN     NaN   NaN
min    2019.0  420.13  198.42  53.89   9.77  10.17  2161.1  2.06
25%    2019.0  420.13  198.42  53.89   9.77  10.17  2161.1  2.06
50%    2019.0  420.13  198.42  53.89   9.77  10.17  2161.1  2.06
75%    2019.0  420.13  198.42  53.89   9.77  10.17  2161.1  2.06
max    2019.0  420.13  198.42  53.89   9.77  10.17  2161.1  2.06

In [ ]:

# for specific
df = pd.read_csv("/content/global_water_consumption.csv", usecols=["Country", "Year"])
df

        Country  Year
0     Indonesia  2022
1     Indonesia  2024
2         Spain  2000
3        Canada  2021
4        Brazil  2022
...         ...   ...
4995      Japan  2018
4996      China  2018
4997         UK  2005
4998  Australia  2005
4999      Italy  2019

[5000 rows x 2 columns]

In [ ]:

# for handling missing values

df = pd.read_csv("/content/global_water_consumption.csv", na_values=["n/a", "Unknown"])

#       PANDAS TUTORIALS

Pandas is the first library to learn in Data Science because we will be dealing with data everytime so we need pandas which is a python library to work with dataset

In [ ]:
# importing pandas
# first step is loading dataset we are taking a CSV file
import pandas as pd
data = pd.read_csv("/content/global_water_consumption.csv")
data

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
0,Indonesia,2022,895.15,489.73,Low,20.78,13.75,34.99,1075.28,3.10
1,Indonesia,2024,502.89,311.95,High,48.51,8.44,32.88,2630.69,1.78
2,Spain,2000,843.39,440.09,Medium,25.16,31.70,34.62,2860.62,4.13
3,Canada,2021,803.34,478.98,High,45.74,6.13,18.99,1725.50,0.61
4,Brazil,2022,416.40,353.91,High,26.58,7.95,31.11,988.44,0.80
...,...,...,...,...,...,...,...,...,...,...
4995,Japan,2018,959.42,143.62,Low,25.19,49.05,10.97,1054.31,4.72
4996,China,2018,642.35,444.26,Medium,66.37,21.20,21.43,1342.62,2.13
4997,UK,2005,848.58,286.60,High,33.97,39.06,31.87,783.17,0.48
4998,Australia,2005,544.67,450.18,Low,64.19,18.74,21.35,1584.80,0.56
4999,Italy,2019,420.13,198.42,Medium,53.89,9.77,10.17,2161.10,2.06

In [ ]:
# Now Data analytics
data.head()

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
0,Indonesia,2022,895.15,489.73,Low,20.78,13.75,34.99,1075.28,3.10
1,Indonesia,2024,502.89,311.95,High,48.51,8.44,32.88,2630.69,1.78
2,Spain,2000,843.39,440.09,Medium,25.16,31.70,34.62,2860.62,4.13
3,Canada,2021,803.34,478.98,High,45.74,6.13,18.99,1725.50,0.61
4,Brazil,2022,416.40,353.91,High,26.58,7.95,31.11,988.44,0.80

In [ ]:
data.tail()

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
4995,Japan,2018,959.42,143.62,Low,25.19,49.05,10.97,1054.31,4.72
4996,China,2018,642.35,444.26,Medium,66.37,21.20,21.43,1342.62,2.13
4997,UK,2005,848.58,286.60,High,33.97,39.06,31.87,783.17,0.48
4998,Australia,2005,544.67,450.18,Low,64.19,18.74,21.35,1584.80,0.56
4999,Italy,2019,420.13,198.42,Medium,53.89,9.77,10.17,2161.10,2.06

In [ ]:
data.shape

(5000, 10)

In [ ]:
data.describe()

,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2012.204400,503.459606,276.034040,50.281704,27.753878,24.814150,1547.793364,2.574684
std,7.205484,284.457947,129.853417,17.397782,12.873524,8.676702,837.198704,1.421690
min,2000.000000,10.050000,50.110000,20.010000,5.000000,10.000000,100.590000,0.100000
25%,2006.000000,259.677500,163.710000,35.277500,16.787500,17.370000,833.552500,1.337500
50%,2012.000000,499.515000,277.445000,50.215000,27.980000,24.800000,1535.670000,2.590000
75%,2018.000000,751.797500,388.975000,65.480000,38.822500,32.322500,2273.147500,3.822500
max,2024.000000,999.680000,499.970000,79.990000,50.000000,40.000000,2998.340000,5.000000

In [ ]:

#function counting number of unique values
data.nunique()

Country                                             20
Year                                                25
Total Water Consumption (Billion Cubic Meters)    4866
Per Capita Water Use (Liters per Day)             4737
Water Scarcity Level                                 3
Agricultural Water Use (%)                        3397
Industrial Water Use (%)                          3033
Household Water Use (%)                           2456
Rainfall Impact (Annual Precipitation in mm)      4956
Groundwater Depletion Rate (%)                     491
dtype: int64

In [ ]:

#function counting null values
data.isnull()

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False

In [ ]:

#function counting the sum of null values
data.isnull().sum()

Country                                           0
Year                                              0
Total Water Consumption (Billion Cubic Meters)    0
Per Capita Water Use (Liters per Day)             0
Water Scarcity Level                              0
Agricultural Water Use (%)                        0
Industrial Water Use (%)                          0
Household Water Use (%)                           0
Rainfall Impact (Annual Precipitation in mm)      0
Groundwater Depletion Rate (%)                    0
dtype: int64

In [ ]:
# All mathematical functions
# import pandas for reading csv file
# import pandas as pd

#reading csv file

#using describe function
print(data.describe())

#using count function
print(data.idxmax())

#using idxmin function
print(data.idxmin())

#count of elements having value 3
print(data.value_counts().head(3))

              Year  Total Water Consumption (Billion Cubic Meters)  \
count  5000.000000                                     5000.000000
mean   2012.204400                                      503.459606
std       7.205484                                      284.457947
min    2000.000000                                       10.050000
25%    2006.000000                                      259.677500
50%    2012.000000                                      499.515000
75%    2018.000000                                      751.797500
max    2024.000000                                      999.680000

       Per Capita Water Use (Liters per Day)  Agricultural Water Use (%)  \
count                            5000.000000                 5000.000000
mean                              276.034040                   50.281704
std                               129.853417                   17.397782
min                                50.110000                   20.010000
25%                               163.710000                   35.277500
50%                               277.445000                   50.215000
75%                               388.975000                   65.480000
max                               499.970000                   79.990000

       Industrial Water Use (%)  Household Water Use (%)  \
count               5000.000000              5000.000000
mean                  27.753878                24.814150
std                   12.873524                 8.676702
min                    5.000000                10.000000
25%                   16.787500                17.370000
50%                   27.980000                24.800000
75%                   38.822500                32.322500
max                   50.000000                40.000000

       Rainfall Impact (Annual Precipitation in mm)  \
count                                   5000.000000
mean                                    1547.793364
std                                      837.198704
min                                      100.590000
25%                                      833.552500
50%                                     1535.670000
75%                                     2273.147500
max                                     2998.340000

       Groundwater Depletion Rate (%)
count                     5000.000000
mean                         2.574684
std                          1.421690
min                          0.100000
25%                          1.337500
50%                          2.590000
75%                          3.822500
max                          5.000000
Country                                             35
Year                                                 1
Total Water Consumption (Billion Cubic Meters)    2930
Per Capita Water Use (Liters per Day)             2599
Water Scarcity Level                                 2
Agricultural Water Use (%)                        2200
Industrial Water Use (%)                          2196
Household Water Use (%)                           4883
Rainfall Impact (Annual Precipitation in mm)      2813
Groundwater Depletion Rate (%)                    2657
dtype: int64
Country                                             29
Year                                                 2
Total Water Consumption (Billion Cubic Meters)    1168
Per Capita Water Use (Liters per Day)             3541
Water Scarcity Level                                 1
Agricultural Water Use (%)                        2702
Industrial Water Use (%)                           416
Household Water Use (%)                            805
Rainfall Impact (Annual Precipitation in mm)      2959
Groundwater Depletion Rate (%)                     335
dtype: int64
Country       Year  Total Water Consumption (Billion Cubic Meters)  Per Capita Water Use (Liters per Day)  Water Scarcity Level  Agricultural Water Use (%)  Industrial Water Use (%)  Household Water Use (%)  Rainfall Impact (Annual Precipitation in mm)  Groundwater Depletion Rate (%)
Argentina     2000  74.12                                           116.91                                 Low                   25.08                       22.13                     22.89                    2730.97                                       3.78                              1
Saudi Arabia  2012  738.36                                          285.79                                 Medium                64.17                       22.03                     33.06                    1757.73                                       1.77                              1
                    973.25                                          469.53                                 High                  23.06                       25.11                     10.21                    2671.63                                       4.91                              1
Name: count, dtype: int64

In [ ]:

#for filling missing values
data = data.fillna(55)
data

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
0,Indonesia,2022,895.15,489.73,Low,20.78,13.75,34.99,1075.28,3.10
1,Indonesia,2024,502.89,311.95,High,48.51,8.44,32.88,2630.69,1.78
2,Spain,2000,843.39,440.09,Medium,25.16,31.70,34.62,2860.62,4.13
3,Canada,2021,803.34,478.98,High,45.74,6.13,18.99,1725.50,0.61
4,Brazil,2022,416.40,353.91,High,26.58,7.95,31.11,988.44,0.80
...,...,...,...,...,...,...,...,...,...,...
4995,Japan,2018,959.42,143.62,Low,25.19,49.05,10.97,1054.31,4.72
4996,China,2018,642.35,444.26,Medium,66.37,21.20,21.43,1342.62,2.13
4997,UK,2005,848.58,286.60,High,33.97,39.06,31.87,783.17,0.48
4998,Australia,2005,544.67,450.18,Low,64.19,18.74,21.35,1584.80,0.56
4999,Italy,2019,420.13,198.42,Medium,53.89,9.77,10.17,2161.10,2.06

In [ ]:
# Syntax: df.drop(['Column1', 'Columns2'], axis=1)
# Drop columns 'B' and 'C'
df = data.drop(['Country', 'Year', 'Household Water Use (%)'], axis=1)
df

,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
0,895.15,489.73,Low,20.78,13.75,1075.28,3.10
1,502.89,311.95,High,48.51,8.44,2630.69,1.78
2,843.39,440.09,Medium,25.16,31.70,2860.62,4.13
3,803.34,478.98,High,45.74,6.13,1725.50,0.61
4,416.40,353.91,High,26.58,7.95,988.44,0.80
...,...,...,...,...,...,...,...
4995,959.42,143.62,Low,25.19,49.05,1054.31,4.72
4996,642.35,444.26,Medium,66.37,21.20,1342.62,2.13
4997,848.58,286.60,High,33.97,39.06,783.17,0.48
4998,544.67,450.18,Low,64.19,18.74,1584.80,0.56
4999,420.13,198.42,Medium,53.89,9.77,2161.10,2.06

In [ ]:
#Working with two different datasets
df2 = pd.read_csv("/content/NVIDIA_Stock_Volatility_2014_2024.csv")
df2

,Date,Close,High,Low,Open,Volume,Daily_Return,Rolling_Volatility,ATR,Rolling_Mean,Upper_Band,Lower_Band
0,2014-01-31,0.370194,0.372316,0.365242,0.365478,335348000,-0.001272,0.016288,0.007461,0.372964,0.385216,0.360713
1,2014-02-03,0.365242,0.373259,0.363827,0.372787,431728000,-0.013376,0.016343,0.007293,0.372752,0.385398,0.360106
2,2014-02-04,0.367364,0.368071,0.363120,0.365006,280692000,0.005810,0.016091,0.006787,0.372398,0.385240,0.359557
3,2014-02-05,0.364063,0.365949,0.361233,0.364770,214676000,-0.008986,0.015657,0.006838,0.371573,0.384325,0.358821
4,2014-02-06,0.368779,0.369722,0.364063,0.364535,168380000,0.012953,0.015622,0.006990,0.370724,0.381627,0.359821
...,...,...,...,...,...,...,...,...,...,...,...,...
2536,2024-02-29,79.089577,79.967326,78.327792,79.071584,507289000,0.018658,0.043006,3.435667,72.529888,82.126502,62.933274
2537,2024-03-01,82.255676,82.276674,79.412481,79.977323,479135000,0.040032,0.043356,3.481655,73.492215,82.927602,64.056827
2538,2024-03-04,85.212837,87.670141,83.695270,84.106149,615616000,0.035951,0.042870,3.628399,74.445794,84.581983,64.309604
2539,2024-03-05,85.943665,86.076636,83.397270,85.249828,520639000,0.008576,0.042105,3.546289,75.277359,86.327912,64.226807
2540,2024-03-06,88.679016,89.702776,87.009413,88.001183,582520000,0.031827,0.041813,3.650700,76.301127,88.341849,64.260405

In [ ]:
# prompt: Merge datasets

import pandas as pd

# Assuming you have two dataframes, df and data2, as defined in your previous code.
# If not, replace these with your actual dataframe names and loading code.

# Method 1: Concatenation (append rows)
merged_df = pd.concat([df, df2], ignore_index=True)

# Method 2: Merging (join based on a common column)
# Identify a common column between the two dataframes.
# Replace 'common_column' with the actual name of the shared column.
# You can choose different join types ('inner', 'outer', 'left', 'right').
# Example using 'inner' join (keeps rows where the common column exists in both datasets):
# merged_df = pd.merge(df, data2, on='common_column', how='inner')

# Method 3: Joining (similar to merge, but uses index by default)
# If you want to join on the index, you can use the .join() method.
# Example:
# merged_df = df.join(data2, how='inner', lsuffix='_df', rsuffix='_data2') # lsuffix and rsuffix to distinguish column names in case of overlap

# Display the merged dataframe
merged_df

# Now you can save the merged DataFrame to a new CSV file if needed:
# merged_df.to_csv("merged_dataset.csv", index=False)

,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%),Date,Close,High,Low,Open,Volume,Daily_Return,Rolling_Volatility,ATR,Rolling_Mean,Upper_Band,Lower_Band
0,895.15,489.73,Low,20.78,13.75,1075.28,3.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,502.89,311.95,High,48.51,8.44,2630.69,1.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,843.39,440.09,Medium,25.16,31.70,2860.62,4.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,803.34,478.98,High,45.74,6.13,1725.50,0.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,416.40,353.91,High,26.58,7.95,988.44,0.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-29,79.089577,79.967326,78.327792,79.071584,507289000.0,0.018658,0.043006,3.435667,72.529888,82.126502,62.933274
7537,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-01,82.255676,82.276674,79.412481,79.977323,479135000.0,0.040032,0.043356,3.481655,73.492215,82.927602,64.056827
7538,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-04,85.212837,87.670141,83.695270,84.106149,615616000.0,0.035951,0.042870,3.628399,74.445794,84.581983,64.309604
7539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-05,85.943665,86.076636,83.397270,85.249828,520639000.0,0.008576,0.042105,3.546289,75.277359,86.327912,64.226807
7540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-06,88.679016,89.702776,87.009413,88.001183,582520000.0,0.031827,0.041813,3.650700,76.301127,88.341849,64.260405

In [ ]:
const = merged_df['Low'].max()
merged_df['High'] = merged_df['Low'].apply(lambda x: x/const)
df

,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Water Scarcity Level,Agricultural Water Use (%),Industrial Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
0,895.15,489.73,Low,20.78,13.75,1075.28,3.10
1,502.89,311.95,High,48.51,8.44,2630.69,1.78
2,843.39,440.09,Medium,25.16,31.70,2860.62,4.13
3,803.34,478.98,High,45.74,6.13,1725.50,0.61
4,416.40,353.91,High,26.58,7.95,988.44,0.80
...,...,...,...,...,...,...,...
4995,959.42,143.62,Low,25.19,49.05,1054.31,4.72
4996,642.35,444.26,Medium,66.37,21.20,1342.62,2.13
4997,848.58,286.60,High,33.97,39.06,783.17,0.48
4998,544.67,450.18,Low,64.19,18.74,1584.80,0.56
4999,420.13,198.42,Medium,53.89,9.77,2161.10,2.06

This is for this tutorial.We will continue this course with the remaining part

Code contributed by Dev!